<%@ Page Title="" Language="C#" MasterPageFile="~/app/MasterPage.Master" AutoEventWireup="true" CodeBehind="GT_Asignacion_Parqueo.aspx.cs" Inherits="AutoStar.app.GT_Asignacion_Parqueo" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <style type="text/css" class="bodyUsuarios">
        body {
            background-image: url('/app/Images/backgrounds/MB20.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment:fixed;
        }
    </style>
    <h2>Parqueos y Bahías</h2>
    <div>
        <asp:Table CssClass="table" ID="Table1" runat="server">
            <asp:TableRow CssClass="tableRow">
                <asp:TableCell CssClass="tableCell">
                    <asp:ImageButton PostBackUrl="~/app/Default.aspx" CssClass="botonFull" ID="ImageButton3" AlternateText="Home" runat="server" ImageUrl="~/app/Images/icons/iconInicio.png" />
                </asp:TableCell>
                <asp:TableCell CssClass="tableCell">
                    <asp:ImageButton CssClass="botonFull" ID="ImageButton1" OnClick="parqueos_Click" AlternateText="Parqueos" runat="server" ImageUrl="~/app/Images/icons/iconParqueos.png" />
                </asp:TableCell>
                <asp:TableCell CssClass="tableCell">
                    <asp:ImageButton CssClass="botonFull" ID="ImageButton2" AlternateText="Bahias" runat="server" ImageUrl="~/app/Images/icons/iconBahias.png" OnClick="btn_bahiasClick" />
                </asp:TableCell>
            </asp:TableRow>
        </asp:Table>
    </div>

    

    <script type="text/javascript">

        //function popup(mylink, windowname) {
        //    if (!window.focus) return true;
        //    var href;
        //    if (typeof (mylink) == 'string')
        //        href = mylink;
        //    else
        //        href = mylink.href;
        //    // You can set the height width scrollbar & menubar according to your 
        //    // requirement
        //    window.open(href, windowname, 'width=700,height=400,scrollbars=yes,resizable=false');
        //    return false;
        //}

    </script>

    <%--<a  href ="http://localhost:1874/app/ppAsignacion_Parqueo.aspx"  onclick="return popup(this,'examplea')">this link</a>--%>

    <%--<asp:ImageButton ID="ImageButton4" runat="server" ImageUrl="~/app/Images/icons/iconBahia.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />--%>


    <asp:Label ID="Label1" CssClass="busquedalbl" runat="server" Text="Seleccionar area:" Visible="False"></asp:Label>
    <asp:DropDownList ID="DropDownList1" runat="server" CssClass="busquedatxt" DataSourceID="SqlDataSource1" DataTextField="descripcion" DataValueField="descripcion" Visible="False" AutoPostBack="true" OnSelectedIndexChanged="onIndexChanged">
        <asp:ListItem>Seleccione el area</asp:ListItem>
    </asp:DropDownList>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:GT_AutoStarConnectionString2 %>" SelectCommand="SELECT descripcion FROM GT_Areas"></asp:SqlDataSource>

    <%--LAYOUT BAHIAS MERCEDES--%>
    <asp:Panel ID="bahiasMercedez" CssClass="divBahiasMB" runat="server" Visible="false">
        <asp:ImageButton CssClass="btnAsignarBahiaMB1" ID="btn_001" AlternateText="Grua" runat="server" ImageUrl="~/app/Images/icons/iconGruaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_001','Search','width=1025,height=410,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo110" ID="btn_110" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_110','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB2" ID="btn_002" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_002','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo111" ID="btn_111" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_111','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB3" ID="btn_003" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_003','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo112" ID="btn_112" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_112','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB4" ID="btn_004" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_004','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo113" ID="btn_113" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_113','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB5" ID="btn_005" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_005','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo114" ID="btn_114" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_114','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB6" ID="btn_006" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_006','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <br />
        <asp:ImageButton CssClass="btnAsignarParqueo115" ID="btn_115" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_115','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB7" ID="btn_007" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_007','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo116" ID="btn_116" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_116','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB8" ID="btn_008" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_008','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo117" ID="btn_117" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_117','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB9" ID="btn_009" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_009','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo118" ID="btn_118" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_118','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB10" ID="btn_010" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_010','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo119" ID="btn_119" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_119','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaMB11" ID="btn_011" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_011','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo120" ID="btn_120" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_120','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
    </asp:Panel>

<%--LAYOUT BAHIAS CDJR--%>
    <asp:Panel ID="bahiasCDJR" CssClass="divBahiasCDJR" runat="server" Visible="false">
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR12" ID="btn_012" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_012','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo121" ID="btn_121" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_121','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR13" ID="btn_013" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_013','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo122" ID="btn_122" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_122','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR14" ID="btn_014" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_014','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo123" ID="btn_123" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_123','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR15" ID="btn_015" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_015','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo124" ID="btn_124" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_124','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR16" ID="btn_016" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_016','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <br />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR17" ID="btn_017" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_017','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo125" ID="btn_125" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_125','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR18" ID="btn_018" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_018','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo126" ID="btn_126" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_126','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR19" ID="btn_019" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_019','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo127" ID="btn_127" AlternateText="Auto" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_127','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR20" ID="btn_020" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_020','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR21" ID="btn_021" AlternateText="Grua" runat="server" ImageUrl="~/app/Images/icons/iconGruaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_021','Search','width=1025,height=410,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR22" ID="btn_128" AlternateText="Grua" runat="server" ImageUrl="~/app/Images/icons/iconGruaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_128','Search','width=1025,height=410,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarBahiaCDJR23" ID="btn_129" AlternateText="Bahia" runat="server" ImageUrl="~/app/Images/icons/iconBahiaLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_129','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
    </asp:Panel>

<%--LAYOUT PARQUEOS--%>
    <asp:Panel ID="parqueo_Nivel_1" CssClass="divParqueoLayout" runat="server" Visible="false">
        <asp:ImageButton CssClass="btnAsignarParqueo1" ID="btn_022" AlternateText="01" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_022','Search','width=1025px,height=410px,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo2" ID="btn_023" AlternateText="02" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_023','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo3" ID="btn_024" AlternateText="03" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_024','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo4" ID="btn_025" AlternateText="04" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_025','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo5" ID="btn_026" AlternateText="05" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_026','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo6" ID="btn_027" AlternateText="06" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_027','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo7" ID="btn_028" AlternateText="07" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_028','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo8" ID="btn_029" AlternateText="08" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_029','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />        
        <asp:ImageButton CssClass="btnAsignarParqueo9" ID="btn_030" AlternateText="09" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_030','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo10" ID="btn_031" AlternateText="10" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_031','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo11" ID="btn_032" AlternateText="11" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_032','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo12" ID="btn_033" AlternateText="12" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_033','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo13" ID="btn_034" AlternateText="13" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_034','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo14" ID="btn_035" AlternateText="14" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_035','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo15" ID="btn_036" AlternateText="15" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_036','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo16" ID="btn_037" AlternateText="16" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_037','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo17" ID="btn_038" AlternateText="17" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_038','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo18" ID="btn_039" AlternateText="18" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_039','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo19" ID="btn_040" AlternateText="19" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_040','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo20" ID="btn_041" AlternateText="20" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_041','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />       
        <asp:ImageButton CssClass="btnAsignarParqueo21" ID="btn_042" AlternateText="21" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_042','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo22" ID="btn_043" AlternateText="22" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_043','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo23" ID="btn_044" AlternateText="23" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_044','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo24" ID="btn_045" AlternateText="24" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_045','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo25" ID="btn_046" AlternateText="25" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_046','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo26" ID="btn_047" AlternateText="26" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_047','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo27" ID="btn_048" AlternateText="27" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_048','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <br />
        <asp:ImageButton CssClass="btnAsignarParqueo28" ID="btn_049" AlternateText="28" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_049','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo29" ID="btn_050" AlternateText="29" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_050','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo30" ID="btn_051" AlternateText="30" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_051','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo31" ID="btn_052" AlternateText="31" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_052','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo32" ID="btn_053" AlternateText="32" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_053','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />  
        <asp:ImageButton CssClass="btnAsignarParqueo33" ID="btn_054" AlternateText="33" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_054','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo34" ID="btn_055" AlternateText="34" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_055','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo35" ID="btn_056" AlternateText="35" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_056','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo36" ID="btn_057" AlternateText="36" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_057','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo37" ID="btn_058" AlternateText="37" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_058','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo38" ID="btn_059" AlternateText="38" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_059','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo39" ID="btn_060" AlternateText="39" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_060','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo40" ID="btn_061" AlternateText="40" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_061','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo41" ID="btn_062" AlternateText="41" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_062','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo42" ID="btn_063" AlternateText="42" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_063','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo43" ID="btn_064" AlternateText="43" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_064','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo44" ID="btn_065" AlternateText="44" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_065','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo45" ID="btn_066" AlternateText="45" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_066','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo46" ID="btn_067" AlternateText="46" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_067','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo47" ID="btn_068" AlternateText="47" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_068','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo48" ID="btn_069" AlternateText="48" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_069','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo49" ID="btn_070" AlternateText="49" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_070','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo50" ID="btn_071" AlternateText="50" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_071','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo51" ID="btn_072" AlternateText="51" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_072','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo52" ID="btn_073" AlternateText="52" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_073','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo53" ID="btn_074" AlternateText="53" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_074','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo54" ID="btn_075" AlternateText="54" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_075','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo55" ID="btn_076" AlternateText="55" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_076','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo56" ID="btn_077" AlternateText="56" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_077','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo57" ID="btn_078" AlternateText="57" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_078','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo58" ID="btn_079" AlternateText="58" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_079','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo59" ID="btn_080" AlternateText="59" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_080','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo60" ID="btn_081" AlternateText="60" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_081','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo61" ID="btn_082" AlternateText="61" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_082','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo62" ID="btn_083" AlternateText="62" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_083','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo63" ID="btn_084" AlternateText="63" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_084','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo64" ID="btn_085" AlternateText="64" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_085','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo65" ID="btn_086" AlternateText="65" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_086','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo66" ID="btn_087" AlternateText="66" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_087','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo67" ID="btn_088" AlternateText="67" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_088','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo68" ID="btn_089" AlternateText="68" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_089','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo69" ID="btn_090" AlternateText="69" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_090','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo70" ID="btn_091" AlternateText="70" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_091','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo71" ID="btn_092" AlternateText="71" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_092','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />        
        <asp:ImageButton CssClass="btnAsignarParqueo72" ID="btn_093" AlternateText="72" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_093','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo73" ID="btn_094" AlternateText="73" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_094','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo74" ID="btn_095" AlternateText="74" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_095','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo75" ID="btn_096" AlternateText="75" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_096','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo76" ID="btn_097" AlternateText="76" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_097','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo77" ID="btn_098" AlternateText="77" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_098','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo78" ID="btn_099" AlternateText="78" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_099','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo79" ID="btn_100" AlternateText="79" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_100','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo80" ID="btn_101" AlternateText="80" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_101','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo81" ID="btn_102" AlternateText="81" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_102','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo82" ID="btn_103" AlternateText="82" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_103','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo83" ID="btn_104" AlternateText="83" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_104','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo84" ID="btn_105" AlternateText="84" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_105','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo85" ID="btn_106" AlternateText="85" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_106','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
        <asp:ImageButton CssClass="btnAsignarParqueo86" ID="btn_107" AlternateText="86" runat="server" ImageUrl="~/app/Images/icons/iconParqueoLibre.png" OnClientClick="window.showModalDialog('http://localhost:1874/app/ppAsignacion_Parqueos.aspx?field1=btn_107','Search','width=550,height=170,left=150,top=200,scrollbars=1,toolbar=no,status=1')" />
    </asp:Panel>

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
