//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStar.app {
    
    
    public partial class GT_Departamentos {
        
        /// <summary>
        /// btn_departamentos_eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btn_departamentos_eliminar;
        
        /// <summary>
        /// btn_departamentos_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btn_departamentos_editar;
        
        /// <summary>
        /// btn_departamentos_nuevo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btn_departamentos_nuevo;
        
        /// <summary>
        /// SqlDataSource1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        
        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        /// <summary>
        /// pnl_departamentos_crear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_departamentos_crear;
        
        /// <summary>
        /// lbl_departamentos_pnl_crear_crear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_crear_crear;
        
        /// <summary>
        /// lbl_departamentos_pnl_crear_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_crear_descripcion;
        
        /// <summary>
        /// txtfld_departamentos_pnl_crear_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_crear_descripcion;
        
        /// <summary>
        /// lbl_departamentos_pnl_crear_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_crear_comentarios;
        
        /// <summary>
        /// txtfld_departamentos_pnl_crear_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_crear_comentarios;
        
        /// <summary>
        /// btn_departamentos_pnl_crear_crear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_departamentos_pnl_crear_crear;
        
        /// <summary>
        /// btn_departamentos_pnl_crear_cancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_departamentos_pnl_crear_cancelar;
        
        /// <summary>
        /// pnl_departamentos_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_departamentos_editar;
        
        /// <summary>
        /// lbl_departamentos_pnl_editar_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_editar_editar;
        
        /// <summary>
        /// lbl_departamentos_pnl_editar_idDepartamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_editar_idDepartamento;
        
        /// <summary>
        /// txtfld_departamentos_pnl_editar_idDepartamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_editar_idDepartamento;
        
        /// <summary>
        /// lbl_departamentos_pnl_editar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_editar_descripcion;
        
        /// <summary>
        /// txtfld_departamentos_pnl_editar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_editar_descripcion;
        
        /// <summary>
        /// lbl_departamentos_pnl_editar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_editar_comentarios;
        
        /// <summary>
        /// txtfld_departamentos_pnl_editar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_editar_comentarios;
        
        /// <summary>
        /// btn_departamentos_pnl_editar_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_departamentos_pnl_editar_editar;
        
        /// <summary>
        /// btn_departamentos_pnl_editar_cancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_departamentos_pnl_editar_cancelar;
        
        /// <summary>
        /// pnl_departamentos_eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_departamentos_eliminar;
        
        /// <summary>
        /// lbl_departamentos_pnl_eliminar_eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_eliminar_eliminar;
        
        /// <summary>
        /// lbl_departamentos_pnl_eliminar_idDepartamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_eliminar_idDepartamento;
        
        /// <summary>
        /// txtfld_departamentos_pnl_eliminar_idDepartamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_eliminar_idDepartamento;
        
        /// <summary>
        /// lbl_departamentos_pnl_eliminar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_eliminar_descripcion;
        
        /// <summary>
        /// txtfld_departamentos_pnl_eliminar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_eliminar_descripcion;
        
        /// <summary>
        /// lbl_departamentos_pnl_eliminar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_departamentos_pnl_eliminar_comentarios;
        
        /// <summary>
        /// txtfld_departamentos_pnl_eliminar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_departamentos_pnl_eliminar_comentarios;
        
        /// <summary>
        /// btn_departamentos_pnl_eliminar_eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_departamentos_pnl_eliminar_eliminar;
        
        /// <summary>
        /// btn_departamentos_pnl_eliminar_cancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_departamentos_pnl_eliminar_cancelar;
    }
}
