//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStar.app {
    
    
    public partial class GT_Prioridad_Orden_Trabajo {
        
        /// <summary>
        /// btn_prioridad_orden_eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btn_prioridad_orden_eliminar;
        
        /// <summary>
        /// btn_prioridad_orden_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btn_prioridad_orden_editar;
        
        /// <summary>
        /// btn_prioridad_orden_nuevo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btn_prioridad_orden_nuevo;
        
        /// <summary>
        /// SqlDataSource2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource2;
        
        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        /// <summary>
        /// SqlDataSource1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        
        /// <summary>
        /// pnl_prioridad_orden_crear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_prioridad_orden_crear;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_crear_crear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_crear_crear;
        
        /// <summary>
        /// lbl_prioridad_orden_crear_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_crear_descripcion;
        
        /// <summary>
        /// txtfld_prioridad_orden_crear_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_crear_descripcion;
        
        /// <summary>
        /// lbl_prioridad_orden_crear_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_crear_comentarios;
        
        /// <summary>
        /// txtfld_prioridad_orden_crear_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_crear_comentarios;
        
        /// <summary>
        /// btn_prioridad_orden_crear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_prioridad_orden_crear;
        
        /// <summary>
        /// btn_prioridad_orden_cancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_prioridad_orden_cancelar;
        
        /// <summary>
        /// pnl_prioridad_orden_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_prioridad_orden_editar;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_editar_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_editar_editar;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_editar_idPrioridad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_editar_idPrioridad;
        
        /// <summary>
        /// txtfld_prioridad_orden_pnl_editar_idPrioridad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_pnl_editar_idPrioridad;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_editar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_editar_descripcion;
        
        /// <summary>
        /// txtfld_prioridad_orden_pnl_editar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_pnl_editar_descripcion;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_editar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_editar_comentarios;
        
        /// <summary>
        /// txtfld_prioridad_orden_pnl_editar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_pnl_editar_comentarios;
        
        /// <summary>
        /// btn_prioridad_orden_pnl_editar_editar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_prioridad_orden_pnl_editar_editar;
        
        /// <summary>
        /// btn_prioridad_orden_pnl_editar_cancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_prioridad_orden_pnl_editar_cancelar;
        
        /// <summary>
        /// pnl_prioridad_orden_eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_prioridad_orden_eliminar;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_eliminar_eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_eliminar_eliminar;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_eliminar_idPrioridad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_eliminar_idPrioridad;
        
        /// <summary>
        /// txtfld_prioridad_orden_pnl_eliminar_idPrioridad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_pnl_eliminar_idPrioridad;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_eliminar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_eliminar_descripcion;
        
        /// <summary>
        /// txtfld_prioridad_orden_pnl_eliminar_descripcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_pnl_eliminar_descripcion;
        
        /// <summary>
        /// lbl_prioridad_orden_pnl_eliminar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_prioridad_orden_pnl_eliminar_comentarios;
        
        /// <summary>
        /// txtfld_prioridad_orden_pnl_eliminar_comentarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtfld_prioridad_orden_pnl_eliminar_comentarios;
        
        /// <summary>
        /// btn_prioridad_orden_pnl_eliminar_Eliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_prioridad_orden_pnl_eliminar_Eliminar;
        
        /// <summary>
        /// btn_prioridad_orden_pnl_eliminar_cancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_prioridad_orden_pnl_eliminar_cancelar;
    }
}
